### ISSUE TITLE
When trying to transfer ships, members where the primary assignment isn't their ship have problems

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#67]
Members who have a primary assignment that isn't the ship to which they are assigned have errors when trying to change ships.

Please report this error via email (bolthole@trm.org) or the Web Portal. Be sure to report exactly what you were doing when the error occurred or the exact steps required to duplicate the error and the error text below. Thank You, The Medusa Dev Team Trying to get property of non-object Stack Trace: #0 /home/forge/medusa.trmn.org/app/controllers/UserChangeRequestController.php(179): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/forge/med...', 179, Array) #1 [internal function]: UserChangeRequestController->approve(Object(ChangeRequest)) #2 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #3 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('approve', Array) #4 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(UserChangeRequestController), Object(Illuminate\Routing\Route), 'approve') #5 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'UserChangeReque...', 'approve') #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(ChangeRequest)) #7 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array) #8 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #10 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #13 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #14 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #15 /home/forge/medusa.trmn.org/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #16 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #17 /home/forge/medusa.trmn.org/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main}

The member who appears to be involved is Commodore Heidi Nelson.

**Comment by eplossl** [comment]
Issue appears to be fixed.  Closing
