### ISSUE TITLE
Chapter reports failing to send

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#69]
Chapter reports are failing to send when there is an echelon in the parent list which does not have an assigned CO.

Error as follows:

Trying to get property of non-object Stack Trace: #0 /home/forge/medusa.trmn.org/app/controllers/ReportController.php(405): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/forge/med...', 405, Array) #1 /home/forge/medusa.trmn.org/app/controllers/ReportController.php(363): ReportController->emailReport('56167e27e4bed8d...') #2 [internal function]: ReportController->sendReport('56167e27e4bed8d...') #3 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #4 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('sendReport', Array) #5 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ReportController), Object(Illuminate\Routing\Route), 'sendReport') #6 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ReportControlle...', 'sendReport') #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('56167e27e4bed8d...') #8 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array) #9 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #11 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #14 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #15 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #16 /home/forge/medusa.trmn.org/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #17 /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #18 /home/forge/medusa.trmn.org/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main}

**Comment by eplossl** [comment]
Found the problem.  The system tries to use $tmpChapter->getCO() without first verifying that the CO value is non-Null.  As such, the error gets thrown, and problems occur.  I have found that the solution is to check that this is non-null before getting into the code to pull the CO email.
